parameters:
#    zizoo_base.example.class: Zizoo\BaseBundle\Example

services:
#    zizoo_base.example:
#        class: %zizoo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
