parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3306'
    database_name: 
    database_user: 
    database_password: 
    mailer_transport: gmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: smtp.gmail.com
    mailer_user: 
    mailer_password: asd
    locale: en
    secret: 
    database_path: null
