parameters:
#    zizoo_boat.example.class: Zizoo\BoatBundle\Example

services:
#    zizoo_boat.example:
#        class: %zizoo_boat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
