<?php

namespace Zizoo\BoatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function getImagesForBoat($boatId)
    {
        $qb = $this->createQueryBuilder('i')
                   ->select('i')
                   ->where('i.boat = :boat_id')
                   ->setParameter('boat_id', $boatId);

        return $qb->getQuery()
                  ->getResult();
    }
}
